# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/A01577421/Desktop/ECE2700/Lab4/project_1/project_1.cache/wt [current_project]
set_property parent.project_path /home/A01577421/Desktop/ECE2700/Lab4/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /home/A01577421/Desktop/ECE2700/Lab4/project_1/project_1.srcs/sources_1/new/dlatch.v
  /home/A01577421/Desktop/ECE2700/Lab4/project_1/project_1.srcs/sources_1/new/DFF.v
  /home/A01577421/Desktop/ECE2700/Lab4/project_1/project_1.srcs/sources_1/new/Latch_dataflow.v
  /home/A01577421/Desktop/ECE2700/Lab4/project_1/project_1.srcs/sources_1/new/DFF_dataflow.v
}
read_xdc /home/A01577421/Desktop/ECE2700/Lab4/project_1/project_1.srcs/constrs_1/new/DFFConstraints.xdc
set_property used_in_implementation false [get_files /home/A01577421/Desktop/ECE2700/Lab4/project_1/project_1.srcs/constrs_1/new/DFFConstraints.xdc]

synth_design -top dlatch -part xc7a35tcpg236-1
write_checkpoint -noxdef dlatch.dcp
catch { report_utilization -file dlatch_utilization_synth.rpt -pb dlatch_utilization_synth.pb }
