set_property SRC_FILE_INFO {cfile:/home/A01577421/Desktop/ECE2700/Lab1/ClockDividerBlock/ClockDividerBlock.srcs/constrs_1/imports/xilinx/Basys3_Master.xdc rfile:../../../ClockDividerBlock.srcs/constrs_1/imports/xilinx/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {clkout}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports clkin]
