set_property SRC_FILE_INFO {cfile:/home/A01577421/Desktop/ECE2700/Lab1/myandgate/myandgate.srcs/constrs_1/imports/xilinx/Basys3_Master.xdc rfile:../../../myandgate.srcs/constrs_1/imports/xilinx/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports {A}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V16 [get_ports {B}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports {F}]
